CREATE TABLE `bugs_fixes` (
	`id` int NOT NULL AUTO_INCREMENT,
	`system` varchar(100) NOT NULL DEFAULT 'moby',
	`issue_id` int NOT NULL,
	`pull_request_id` int NOT NULL,
	`number` int NOT NULL,
	`title` text,
	`body` text,
	`issue_url` text,
	`pull_request_url` text,
	`created_at` varchar(100) NOT NULL,
	`closed_at` varchar(100),
	`updated_at` varchar(100),
	`state` varchar(100),
	`labels` text,
	`comments` int,
	`comments_url` text,
	`commits` int,
	`additions` int,
	`deletions` int,
	`changed_files` int,
	`commits_data` text,
	`bug_report_url` varchar(250),
	`bug_fix_url` varchar(250),
	`symptoms` varchar(50),
	`root_causes` varchar(50),
	`impact` varchar(50),
	`consequences` varchar(50),
	`fixes` varchar(50),
	`system_dependent` varchar(50),
	`triggers` varchar(50),
	`characteristics` varchar(50),
	`notes` text,
	PRIMARY KEY (`id`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_0900_ai_ci;
